# Generated by Django 4.1 on 2024-05-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_blog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='spendPrice',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
